lab5_p1: p1.c
	gcc -o main p1.c
	./main

lab5_p2: p2.c
	gcc -o main p2.c
	./main

lab5_p3: p3.c
	rm -f b_link_hard.txt b_link_soft.txt
	gcc -o main p3.c
	./main

lab5_p4: p4.c
	gcc -o main p4.c
	./main

.PHONY: clean

clean:
	rm -f main b_link_hard.txt b_link_soft.txt